#List of random facts
facts = [
   "Cats have a unique grooming behavior called allogrooming, where they groom each other.",
    "The honeybee is the only insect that produces food eaten by humans.",
    "A group of owls is called a parliament.",
    "The world's largest recorded snowflake was 15 inches wide and 8 inches thick.",
    "Bananas are berries, but strawberries are not.",
    "Elephants are the only animals that can't jump.",
    "A flamingo can only eat when its head is upside down.",
    "Octopuses have three hearts.",
    "A panda's diet consists almost entirely of bamboo.",
    "The unicorn is the national animal of Scotland.",
    "A group of flamingos is called a flamboyance.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "In Japan, there are more pets than children.",
    "The first computer mouse was made of wood.",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "A baby spider is called a spiderling.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "In Japan, there are more pets than children.",
    "The first computer mouse was made of wood.",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "A baby spider is called a spiderling.",
    "Polar bears have black skin.",
    "Hippopotamus milk is pink.",
    "Cows have best friends.",
    "The world's largest sand island is Fraser Island in Australia.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
    "There is a country with no rivers – Saudi Arabia.",
    "The Canary Islands are named after dogs, not birds.",
    "Bolivia has two capital cities: La Paz and Sucre.",
    "The smell of freshly-cut grass is actually a plant distress call.",
    "A 'jiffy' is an actual unit of time: 1/100th of a second.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "In Japan, there are more pets than children.",
    "The first computer mouse was made of wood.",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "A baby spider is called a spiderling.",
    "Polar bears have black skin.",
    "Hippopotamus milk is pink.",
    "Cows have best friends.",
    "The world's largest sand island is Fraser Island in Australia.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "The Canary Islands are named after dogs, not birds.",
    "Bolivia has two capital cities: La Paz and Sucre.",
    "The smell of freshly-cut grass is actually a plant distress call.",
    "A 'jiffy' is an actual unit of time: 1/100th of a second.",
    "Venus rotates in the opposite direction to most planets in our solar system.",
    "Sharks are the only fish species that can blink with both eyes.",
    "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
    "The average person spends six months of their life waiting for red lights to turn green.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "Cleopatra lived closer to the invention of the iPhone than to the building of the Great Pyramid.",
    "Bananas are berries, but strawberries are not.",
    "Humans and giraffes have the same number of neck vertebrae.",
    "Banging your head against a wall burns 150 calories an hour.",
    "Tears have different chemical compositions depending on the reason you cry.",
    "Koalas sleep up to 22 hours a day.",
    "The oldest known species on Earth is a horseshoe crab called Limulus polyphemus.",
    "The average person walks the equivalent of three times around the world in a lifetime.",
    "The strongest muscle in the human body is the tongue.",
    "The tiny indestructible animal known as the tardigrade can survive in space, boiling water, and intense radiation.",
    "Every year, the Netherlands sends 20,000 tulip bulbs to Canada to thank them for their aid in the Second World War.",
    "Antibiotics can't treat viral infections like the common cold.",
    "The Great Pyramid of Giza was originally covered in casing stones made of highly polished Tura limestone.",
    "Dogs have an extraordinary sense of smell, capable of detecting scents at concentrations of one part per trillion.",
    "The shortest war in history was between Britain and Zanzibar on August 27, 1896. Zanzibar surrendered after 38 minutes.",
    "In Japan, there are more pets than children.",
    "The first computer mouse was made of wood.",
    "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    "A baby spider is called a spiderling.",
    "Polar bears have black skin.",
    "Hippopotamus milk is pink.",
    "Cows have best friends.",
    "The world's largest sand island is Fraser Island in Australia.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "Russia has a larger surface area than Pluto.",
    "The Canary Islands are named after dogs, not birds.",
    "Bolivia has two capital cities: La Paz and Sucre.",
    "The human brain takes in 11 million bits of information every second but is aware of only 40.",
    "The smell of freshly-cut grass is actually a plant distress call.",
]